version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  sonar:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - sonarcloud/scan
  test:
    docker:
      - image: circleci/python:3.6
    steps:
#      - checkout
#      - run:
#          command: |
#            pip install -r requirements.txt
#            sudo apt-get install libsndfile1
#          name: Installing requirements
#      - run:
#          environment:
#            - DEVICE_NAME: cpu
#          command: python -m unittest -v
#          name: Running tests
      - run:
          command: exit 0
  infrastructure-providing-and-deploy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform init
          command: |
            cd IAC &&
            terraform init
      - run:
          name: Terraform provide and deploy
          command: |
            cd IAC &&
            terraform apply -auto-approve \
              -var="ecr_image_tag=${CIRCLE_SHA1}"\
              -var="repository_name=${CIRCLE_PROJECT_REPONAME,,}"

workflows:
  main:
    jobs:
      - sonar
      - test
      - aws-ecr/build-and-push-image:
          context: TerraformContext
          repo: "${CIRCLE_PROJECT_REPONAME,,}"
          tag: "${CIRCLE_SHA1}"
          create-repo: true
          aws-access-key-id: TF_VAR_aws_provider_key
          aws-secret-access-key: TF_VAR_aws_provider_secret
          account-url: TF_VAR_aws_ecr_account_url
          requires:
            - sonar
            - test
          filters:
            branches:
              only:
                - master
                - qa
      - infrastructure-providing-and-deploy:
          context:
            - TerraformContext
          requires:
            - aws-ecr/build-and-push-image


